<?php

function F_InitAll($config, $MySQL_connection, $Username, $Password){
	if(F_Check_AdminLogin($config, $Username, $Password)){
		$MySQL_connection->query("DROP TABLE `" . $config['MySQL_Base'] . "`.`TW_account`, `" . $config['MySQL_Base'] . "`.`TW_news`, `" . $config['MySQL_Base'] . "`.`TW_poll_item`, `" . $config['MySQL_Base'] . "`.`TW_poll_data`, `" . $config['MySQL_Base'] . "`.`TW_forum_class`, `" . $config['MySQL_Base'] . "`.`TW_forum_subject`, `" . $config['MySQL_Base'] . "`.`TW_forum_post`, `" . $config['MySQL_Base'] . "`.`TW_shop_class`, `" . $config['MySQL_Base'] . "`.`TW_shop_item`, `" . $config['MySQL_Base'] . "`.`TW_shop_item_cmd`, `" . $config['MySQL_Base'] . "`.`TW_live_chat_class`, `" . $config['MySQL_Base'] . "`.`TW_live_chat_msg`, `" . $config['MySQL_Base'] . "`.`TW_IP`)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_account`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `UUID` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `email` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `username` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `password` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `rank` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `level` INT, `coins` INT, `last_connection` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `last_ip` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `first_ip` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `register_date` DATETIME DEFAULT CURRENT_TIMESTAMP)"); 
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_news`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,`title` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `under_title` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `post` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `senderID` INT, `date` DATETIME DEFAULT CURRENT_TIMESTAMP)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_poll_item`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,`title` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `question` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `senderID` INT, `date` DATETIME DEFAULT CURRENT_TIMESTAMP)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_poll_data`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `poll_ID` INT,`proposal` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,  `selected_count` INT)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_forum_class`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,`title` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `under_title` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `unresolver_subject_count` INT)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_forum_post`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `CID` INT, `title` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `under_title` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `status` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `date` DATETIME DEFAULT CURRENT_TIMESTAMP)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_forum_subject`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `SID` INT, `post` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `senderID` INT, `date` DATETIME DEFAULT CURRENT_TIMESTAMP)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_shop_class`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `name` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `description` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_shop_item`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `CID` INT, `name` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `price` DOUBLE, `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `rate` INT)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_shop_item_cmd`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `CID` INT, `IID` INT, `cmd` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_live_chat_class`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `topic` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `connected` INT)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_live_chat_msg`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `CID` INT,`msg` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `senderID` INT, `date` DATETIME DEFAULT CURRENT_TIMESTAMP)");
		$MySQL_connection->query("CREATE TABLE `" . $config['MySQL_Base'] . "`.`TW_IP`(`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT, `IP` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `account_count` INT, `last_connection` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, `first_connection` DATETIME DEFAULT CURRENT_TIMESTAMP)");
		return true;
	}else{
		//echo("<br>Uncrypt result : " . F_Decrypt($Password, $config['Admin_Password']) . "<br>Username Admin : " . $config['Admin_Username'] . " <br>Username User : " . $Username . "<br>Password User : " . $Password);
		return false;
	}
}
?>